SUFGridLocals = {
	-- Aura group names
	["Druid"] = "Druid",
	
	-- Configuration
	["Grid"] = "Grid",
	["Raid indicators"] = "Raid indicators",
	["Indicators"] = "Indicators",
	["Enable vertical health"] = "Enable vertical health",
	["Changes the health bar to go from top -> bottom instead of right -> left when players lose health."] = "Changes the health bar to go from top -> bottom instead of right -> left when players lose health.",
	["Enable debuff coloring"] = "Enable debuff coloring",
	["If the player is debuffed with something you can cure, the health bar will be colored with the debuff type."] = "If the player is debuffed with something you can cure, the health bar will be colored with the debuff type.",
		
	["Show inside"] = "Show inside",
	["Indicator this aura should be displayed in."] = "Indicator this aura should be displayed in.",
	["Priority"] = "Priority",
	["If multiple auras are shown in the same indicator, the higher priority one is shown first."] = "If multiple auras are shown in the same indicator, the higher priority one is shown first.",
	["Indicator color"] = "Indicator color",
	["Solid color to use in the indicator, only used if you do not have use aura icon enabled."] = "Solid color to use in the indicator, only used if you do not have use aura icon enabled.",
	["Show aura icon"] = "Show aura icon",
	["Instead of showing a solid color inside the indicator, the icon of the aura will be shown."] = "Instead of showing a solid color inside the indicator, the icon of the aura will be shown.",
	["Show aura duration"] = "Show aura duration",
	["Shows a cooldown wheel on the indicator with how much time is left on the aura."] = "Shows a cooldown wheel on the indicator with how much time is left on the aura.",
	["Only show self cast auras"] = "Only show self cast auras",
	["Only auras you specifically cast will be shown."] = "Only auras you specifically cast will be shown.",
	["Only show if missing"] = "Only show if missing",
	["Only active this aura inside an indicator if the group member does not have the aura."] = "Only active this aura inside an indicator if the group member does not have the aura.",
	["Are you sure you want to delete this aura?"] = "Are you sure you want to delete this aura?",
	["Auras"] = "Auras",
	["Add aura"] = "Add aura",
	["Add new aura"] = "Add new aura",
	["Aura name"] = "Aura name",
	["The exact buff or debuff name, this is case sensitive."] = "The exact buff or debuff name, this is case sensitive.",
	["Aura group"] = "Aura group",
	["What group this aura belongs to, this is where you will find it when configuring."] = "What group this aura belongs to, this is where you will find it when configuring.",
	["New aura group"] = "New aura group",
	["Allows you to enter a new aura group."] = "Allows you to enter a new aura group.",
	["Miscellaneous"] = "Miscellaneous",
	["Are you sure you want to delete this indicator?"] = "Are you sure you want to delete this indicator?",
	["Indicator name"] = "Indicator name",
	["Add indicator"] = "Add indicator",
	["Indicators"] = "Indicators",
	["Add new indicator"] = "Add new indicator",
}